/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.11.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

dependencies {
	implementation(project(":util"))

    // https://javalin.io/
    implementation(libs.javalin)
    // log features to javalin (to resolve a warning)
    implementation(libs.slf4j.simple)

    // add Swagger page
    annotationProcessor(libs.openapi.processor)
    implementation(libs.openapi.plugin)
    implementation(libs.swagger.plugin)

	// this backend manage a sqlite database file
	implementation(libs.jdbc.sqlite)
}

// Apply a specific Java toolchain to ease working on different environments.
java.toolchain.languageVersion.set(JavaLanguageVersion.of(21))

group = "group14.pissir"

val mainClassName = "Backend"

// Define the main class for the application.
application.mainClass = "$group.backend.$mainClassName"

val jarBaseName = "backend"

val appJar = projectDir.resolve("build/libs/$jarBaseName.jar")

tasks {
	named<JavaExec>("run") {
		standardInput = System.`in`
	}

	jar {
		dependsOn(":util:jar")
		manifest.attributes["Main-Class"] = application.mainClass.get()
		from(configurations.runtimeClasspath.get().map(::zipTree))
		duplicatesStrategy = DuplicatesStrategy.EXCLUDE
		archiveBaseName = jarBaseName
		println("[GRADLE] INFO created jar file. Execute \"java -jar $appJar\"")
	}

	register<Exec>("runJar") {
		dependsOn("jar")
		commandLine("java", "-jar", appJar)
		standardInput = System.`in`
	}
}
