/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.11.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id("application")
}

dependencies {
	implementation(project(":util"))

    // https://javalin.io/
    implementation(libs.javalin)
    // log features to javalin
    implementation(libs.slf4j.simple)
	// jackson-databind
	implementation("com.fasterxml.jackson.core:jackson-databind:2.17.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java.toolchain.languageVersion.set(JavaLanguageVersion.of(21))

group = "group14.pissir"

val mainClassName = "Debug"

// Define the main class for the application.
application.mainClass = "$group.iot.debug.$mainClassName"

val jarBaseName = "debug"

val appJar = projectDir.resolve("build/libs/$jarBaseName.jar")

tasks {
	named<JavaExec>("run") {
		standardInput = System.`in`
	}

	jar {
		dependsOn(":util:jar")
		manifest.attributes["Main-Class"] = application.mainClass.get()
		from(configurations.runtimeClasspath.get().map(::zipTree))
		duplicatesStrategy = DuplicatesStrategy.EXCLUDE
		archiveBaseName = jarBaseName
		println("[GRADLE] INFO created jar file. Execute \"java -jar $appJar\" to run.")
	}

	register<Exec>("runJar") {
		dependsOn("jar")
		println("[GRADLE] INFO executing \"java -jar $appJar\"")
		commandLine("java", "-jar", appJar)
		standardInput = System.`in`
	}
}
