// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(SmartParkingContext))]
    partial class SmartParkingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Backend.Models.PriceType", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("PriceTypes");

                    b.HasData(
                        new
                        {
                            Name = "PARKING"
                        },
                        new
                        {
                            Name = "CHARGING"
                        });
                });

            modelBuilder.Entity("Backend.Models.SlotStatus", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("SlotStatuses");

                    b.HasData(
                        new
                        {
                            Name = "FREE"
                        },
                        new
                        {
                            Name = "OCCUPIED"
                        });
                });

            modelBuilder.Entity("Backend.Models.UserType", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            Name = "ADMIN"
                        },
                        new
                        {
                            Name = "BASE"
                        },
                        new
                        {
                            Name = "PREMIUM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
